name: app_vendas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  uuid: ^4.0.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  http: ^1.2.1
  sqflite: ^2.3.0
  intl: ^0.18.1
  path: ^1.8.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo_mastigadores.png
